---
language: node_js
node_js:
  - "6"

sudo: false
dist: trusty

addons:
  chrome: stable

cache:
  directories:
    - $HOME/.npm

env:
  global:
    - JOBS=1

before_install:
  - npm config set spin false

script:
  - npm run lint:js
  - npm test

deploy:
  - provider: script
    skip_cleanup: true
    script: node_modules/.bin/ember deploy production --verbose
    on:
      branch: master
