---
language: node_js
node_js:
  - "10"

dist: xenial

addons:
  chrome: stable

cache: npm

env:
  global:
    - JOBS=1
    - secure: MgFVY1WpkXJvSjnSC47dGAgMoaT0dNAvX9wiw715z2gaTKvZmrZX3YKoeyc4IcdR7upSFbH5DT3tg38bAivCOowB4juTp1T2kjNwzaX0/y3CSBFaYNWt1dGqr3bb5Qq7mHOp609cj1iaGfR5ifnD+Cco5PVL+JZTbuBpZg40TDkB59969T2XS9E5bN/vhoJaFvNTdQ5ptLCxjd+osCnx3GeOMVyvavmUT3LvWe7pOtZdlONipfNi0m6Y8gBKjC4bBQpO8w3TyM5LR6AzsmvTq2/V5KPknzy892q2CPcYq1gd8pIJ0BdDiolVAKoz3wSPpXuM2BA3mahmstkzlPZiDNybSYbFWFmlJJQ26XBBDpQRwfkUJpMwaojX0NlaFEDYWBDs4BHHO6XCEtiFsULD/tV5p72ubZoY1wB6RjdWEUEkcn3IYsFHHIxZt2k09rjhio3PsAJ7AIU8KjkI+ApTh5p36g+RdZALxEmgRKkHvX0Db03SRMgb19bElgzy1RT9+xKwJMjgeQ/08lb4I5xKwp4gwkKjVrFMZytD3wUKYFJOMUpnKa57i/We4gFtD+tNEKNZqE+3lsYEWW7durXlj28dmaWjWhPhz079zRvBlR7WBnwl+81nzuG7/C++R+Yrg6h6xW7PLIk+uvcDU7FThE07ik7AujdSFkls9X5/tC0=

branches:
  only:
    - master

script:
  - npm test

before_deploy:
  - git config --global user.email "brunoocasali@gmail.com"
  - git config --global user.name "Travis-CI <brunoocasali>"
  - git config credential.helper "store --file=.git/credentials"
  - echo "https://${GH_TOKEN}:@github.com" > .git/credentials

deploy:
  - provider: script
    skip_cleanup: true
    script: node_modules/.bin/ember deploy production --verbose
    on:
      branch: master
