---
language: node_js
node_js:
  - "6"

sudo: false
dist: trusty

addons:
  chrome: stable

cache:
  directories:
    - $HOME/.npm

env:
  global:
    - JOBS=1

before_install:
  - npm config set spin false

script:
  - npm run lint:js
  - npm test

deploy:
  provider: script
  script: npm run deploy
  on:
    branch: master
